// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "/data/data/com.termux/files/home/nuxt3-awesome/app/app.config";
import type { default as appConfig1 } from "/data/data/com.termux/files/home/nuxt3-awesome/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}